/**
 * The complete index of everything in aby that influences learning.
 *
 * This union is hand-written on purpose. Deriving it from the bindings registry
 * (`keyof typeof BINDINGS`) is circular — `Binding` references `ParamId` — and
 * TypeScript rejects it outright. Writing it by hand turns that limitation into
 * the stronger guarantee: `bindings/index.ts` is checked against
 * `{ [K in ParamId]: Binding<K> }`, so a declared parameter with no binding is a
 * *compile* error, not just an unbound number nobody noticed.
 *
 * Adding a line here is the deliberate act. It is meant to be slightly annoying.
 */

/** Parameters with a code site: an exported const the drift check can read back. */
export type CodeParamId =
  | "schedule/min-ease"
  | "schedule/default-ease"
  | "schedule/mastery-threshold"
  | "schedule/mastery-alpha"
  | "grade/lapse-threshold"
  | "embed/dim"
  | "verify/check-timeout-ms";

/**
 * Parameters with no code site: assumptions other bindings depend on.
 *
 * These exist because a number can encode a decision without ever appearing as a
 * decision. `MASTERY_ALPHA = 0.4` is really "four correct answers should cross the
 * threshold" — and *that* is the pedagogical choice. Naming it makes it auditable
 * and puts it on the ratchet where it belongs.
 *
 * An implied parameter that nothing references is dead weight, so the test
 * requires each one to be an input to some other binding.
 */
export type ImpliedParamId =
  | "mastery/crossings-to-threshold"
  | "assess/questions-per-topic-min"
  | "assess/questions-per-topic-max"
  | "roadmap/node-count-min"
  | "roadmap/node-count-max"
  | "roadmap/skip-at-or-above-level"
  | "grade/score-partial-credit";

/**
 * Normative units of model-facing prose — every rule the tutor is told to follow.
 *
 * Ids are `prefix/heading-slug/first-six-words`, generated by `extractNormativeUnits`
 * rather than chosen: an id nobody picked cannot drift from the text it names.
 * Reordering the bullets in SKILL.md is free; rewording a rule changes its id and
 * the coverage test says so.
 */
export type ProseParamId =
  | "tutor/assessing/the-point-is-to-find-the"
  | "tutor/assessing/one-question-at-a-time-ask"
  | "tutor/assessing/start-midrange-and-move-correct-and"
  | "tutor/assessing/ask-them-to-explain-or-predict"
  | "tutor/assessing/stop-when-placed-usually-36-questions"
  | "tutor/assessing/record-what-you-actually-saw-evidence"
  | "tutor/assessing/never-call-abyrecordassessment-for-a-topic"
  | "tutor/assessing/say-what-you-concluded-and-let"
  | "tutor/building-the-roadmap/nodes-are-things-you-can-teach"
  | "tutor/building-the-roadmap/start-from-what-they-already-know"
  | "tutor/building-the-roadmap/820-nodes-is-usually-right-if"
  | "tutor/building-the-roadmap/ids-are-stable-slugs-btreesplits-reuse"
  | "tutor/building-the-roadmap/send-the-whole-roadmap-on-every"
  | "tutor/building-the-roadmap/if-the-tool-rejects-a-cycle"
  | "tutor/teaching/before-writing-call-abyfindsimilar-for-the"
  | "tutor/teaching/a-lesson-should"
  | "tutor/teaching/lead-with-the-problem-the-concept"
  | "tutor/teaching/use-one-worked-example-the-learner"
  | "tutor/teaching/name-the-failure-mode-the"
  | "tutor/teaching/stay-in-one-sittings-worth-of"
  | "tutor/teaching/then-call-abysavelesson-with-the-full"
  | "tutor/quizzing/call-abyfindsimilar-first-and-avoid-reasking"
  | "tutor/quizzing/ask-for-application-or-prediction-not"
  | "tutor/quizzing/one-question-at-a-time-wait"
  | "tutor/quizzing/grade-honestly-against-the-answer-key"
  | "tutor/quizzing/tell-them-what-was-wrong-and"
  | "tutor/quizzing/when-abyrecordquiz-reports-lapsed-true-dont"
  | "tutor/tone/direct-and-warm-do-not-congratulate";

export type ParamId = CodeParamId | ImpliedParamId | ProseParamId;
